import Head from 'next/head';
import { page } from 'component-tracking-anotation';
import { Button } from 'ui-toolkit';
page();

export default function Home() {
  const buttonProps = { style: { background: '#ff0000' } };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Main Web Page</h1>
        <Button theme="primary">Hello</Button>
        <Button
          theme="secondary"
          style={{
            background: '#ffffff',
            fontSize: 24,
            height: 50,
            marginTop: 12,
            marginBottom: 12,
          }}
        >
          Custom Style
        </Button>
        <Button {...buttonProps}>TEST</Button>
      </main>
    </>
  );
}
